# Generated by Django 5.2.17 on 2026-10-01 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('principio_activo', models.CharField(blank=True, max_length=150)),
                ('lote', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('precio_caja', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='catalogo.categoria')),
            ],
            options={
                'ordering': ['nombre_comercial'],
                'constraints': [models.UniqueConstraint(fields=('nombre_comercial', 'lote'), name='insumo_nombre_lote_unico')],
            },
        ),
    ]
