# Generated by Django 5.2.17 on 2026-10-01 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.insumo'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.carro'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.insumo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_despacho', to='pedidos.solicitud'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.solicitud'),
        ),
        migrations.AddConstraint(
            model_name='itemcarro',
            constraint=models.UniqueConstraint(fields=('carro', 'insumo'), name='item_unico_por_carro'),
        ),
    ]
